version: '3.7'

services:
  dev-deploy: &dev-deploy
    image: quay.io/nyulibraries/illiad-templates:development
    build: .
    environment:
      FTP_CMD: "put ./index-dev.html -o index.html; put ./error.asp; mput ./dist/views/*.html; mirror -R ./sass/lib/images; cd ./javascripts; put ./dist/javascripts/illiad.js; cd ../stylesheets; put ./dist/stylesheets/illiad.css; exit"
    env_file:
      - test.env

  dev-setup:
    <<: *dev-deploy
    build: .
    environment:
      FTP_CMD: "mkdir -p ./javascripts; mkdir -p ./stylesheets; mkdir -p ./images; exit;"

  prod-deploy: &prod-deploy
    image: quay.io/nyulibraries/illiad-templates:master
    build: .        
    environment:
      FTP_CMD: "put ./index-prod.html -o index.html; put ./error.asp; mput ./dist/views/*.html; mirror -R ./sass/lib/images; cd ./javascripts; put ./dist/javascripts/illiad.js; cd ../stylesheets; put ./dist/stylesheets/illiad.css; exit"
      FTP_USERNAME:
      FTP_PASSWORD:
      FTP_HOST:
      FTP_PROXY:

  prod-setup:
    <<: *prod-deploy
    build: .
    environment:
      FTP_CMD: "mkdir -p ./javascripts; mkdir -p ./stylesheets; mkdir -p ./images; exit;"
