---
views:
  - Layout:
    - ArticleRequest
    - BookChapterRequest
    - LoanRequest
    - GenericRequestMicroform
    - OtherRequest
    - EditArticleRequest
    - EditBookChapterRequest
    - EditLoanRequest
    - EditGenericRequestMicroform
    - EditOtherRequest
    - IlliadMainMenu
    - ViewOutstandingRequests
    - ElectronicDelivery
    - ViewRenewCheckedOutItems
    - ViewResubmitCancelledRequests
    - ViewRequestHistory
    - ViewAllRequests
    - ViewNotifications
    - DetailedInformation
    - ViewDefaultDetailed
    - ViewDetailedInformation
    - ViewNotificationsDetail
    - ViewRenewCheckedOutDetailedInformation
    - ViewResubmitDetailedInformation
    - ViewSearchResults
    - ElectronicDeliveryUndelete
    - Error
    - NewAuthRegistration
  - include_header
  - include_menu
  - include_footer
  - include_javascripts
  - include_stylesheets
  - include_meta
  - include_request_buttons
