---
views:
  - Layout:
    - ArticleRequest
    - BookChapterRequest
    - LoanRequest
    - GenericRequestPeriodicalVolume
    - ThesisRequest
    - GenericRequestAudioVisual
    - GenericRequestMusicalScore
    - GenericRequestMicroform
    - OtherRequest
    - EditArticleRequest
    - EditBookChapterRequest
    - EditLoanRequest
    - EditGenericRequestPeriodicalVolume
    - EditThesisRequest
    - EditGenericRequestAudioVisual
    - EditGenericRequestMusicalScore
    - EditGenericRequestMicroform
    - EditOtherRequest
    - IlliadMainMenu
    - ViewOutstandingRequests
    - ElectronicDelivery
    - ViewRenewCheckedOutItems
    - ViewResubmitCancelledRequests
    - ViewRequestHistory
    - ViewAllRequests
    - ViewNotifications
    - DetailedInformation
    - ViewDefaultDetailed
    - ViewDetailedInformation
    - ViewNotificationsDetail
    - ViewRenewCheckedOutDetailedInformation
    - ViewResubmitDetailedInformation
    - ViewSearchResults
    - ElectronicDeliveryUndelete
    - Error
    - NewAuthRegistration
  - IncludeHeader
  - IncludeMenu
  - IncludeFooter
  - IncludeJavascripts
  - IncludeStylesheets
  - IncludeMeta
  - IncludeRequestButtons
