version: 2.1

machine-defaults: &machine-defaults
  machine:
    image: ubuntu-2204:current
  working_directory: ~/app

env-vars: &env-vars
  environment:
    IMAGE_NAME: illiad-templates

aws_env: &aws_env
  run:
    name: Export AWS env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker compose -f docker-compose.build.yml build

auth_quay: &auth_quay
  run:
    name: Authenticate Quay 
    command: |
      docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker pull quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH} || docker pull quay.io/nyulibraries/${IMAGE_NAME}:latest

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

hermes_deploy: &hermes_deploy
  run:
    name: Deploy via Hermes
    command: |
      export TAG=${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master createJob -job=illiad-templates -tag=$TAG
      # docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_TIMEOUT=6m quay.io/nyulibraries/hermesclient:master jobStatus -job=illiad-templates
      timeout 1m sh -c 'until docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master jobStatus -job=illiad-templates -wait=false; do sleep 5; done'

compile: &compile
  run:
    name: Compile and copy CSS and JS assets 
    command: |
      docker compose run compile
      docker cp `docker ps -a --filter "name=illiad-templates-compile-run-" --format "{{.Names}}"`:/app/dist .

# Note that `aws s3 sync ... --exact-timestamps` only works for downloads from S3,
# not uploads: https://github.com/aws/aws-cli/issues/4460.  The only safe way
# to update is to upload absolutely everything using `cp` and then deleting
# removed files using `sync --delete`.  There are many other open GitHub issues
# related to this behavior.  Here's another: https://github.com/aws/aws-cli/issues/3273.
aws-sync-s3: &aws-sync-s3
  run:
    name: Deploy to S3
    command: |
      aws s3 cp --recursive --exclude "*" --include "javascripts/illiad.js" --include "stylesheets/illiad.css" dist ${S3_URI}/illiad && \
      aws s3 sync --delete --exclude "*" --include "javascripts/illiad.js" --include "stylesheets/illiad.css" dist ${S3_URI}/illiad

jobs:
  build-image-dev:
    <<: [*machine-defaults, *env-vars]
    steps:
      - checkout
      - <<: *auth_quay
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *push_docker
      - <<: *compile
      - <<: *aws_env
      - <<: *aws-sync-s3
  
  build-image-prod:
    <<: [*machine-defaults, *env-vars]
    steps:
      - checkout
      - <<: *auth_quay
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *push_docker
      - <<: *compile
      - <<: *aws_env
      - <<: *aws-sync-s3

  deploy-dev:
    <<: [*machine-defaults, *env-vars]
    steps:
      - <<: *auth_quay
      - run:
          name: Export Hermes Dev env vars
          command: |
            echo 'export HERMES_HOST=https://hermes-dev.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_DEV' >> $BASH_ENV
      - <<: *hermes_deploy

  deploy-prod:
    <<: [*machine-defaults, *env-vars]
    steps:
      - <<: *auth_quay
      - run:
          name: Export Hermes Prod env vars
          command: |
            echo 'export HERMES_HOST=https://hermes.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_PROD' >> $BASH_ENV
      - <<: *hermes_deploy

workflows:
  deploy:
    jobs:
      - build-image-dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - build-image-prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          requires:
            - build-image-dev
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
            - build-image-prod
          filters:
            branches:
              only:
                - master
